const string = "   This is a string    ";
let str = "String 2"
// Define the length of the string........
console.log(string.length);
// Find the perticular string......
console.log(string.charAt(3));
//Convert the string into lowercase........
console.log(string.toLowerCase());
//Convert the string to uppper case..........
console.log(string.toUpperCase());
//Remove the spaces from string .............
console.log(string.trim());
//String slice print a perticular part of string...
console.log(string.slice(3,7))
//String concatination........
console.log(string.concat(str))
console.log(string+str) //2nd method by using "+"sign
//String replace
console.log(string.replace("a","A"));
console.log(string.replaceAll("s","S"))